### ISSUE TITLE
add branding to action.yml

### ISSUE THREAD

**Issue by zepatrik** [ory/closed-reference-notifier#11]
You can't use custom icons or colors but there are a view to choose from.
https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#branding

**Comment by zepatrik** [comment]
proposal:
```yml
branding:
  icon: hash  
  color: red
```
red for closed, hash for issue/pr number
